project:
  type: website
  output-dir: docs
  
website:
  title: "统计学64学时"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - chap1.qmd
      - chap2.qmd
      - chap3.qmd
      - chap6.qmd
      - chap7.qmd
      - chap8.qmd
      - chap9.qmd
      - chap10.qmd
      - chap11.qmd
      - case.qmd
    tools:
      - icon: envelope
        href: lizongzhang9@qq.com
  page-footer:
    right: "Statistics: turning data into insights."
    left: "&copy; Copyright 2025, Li Zongzhang"
format:
  html:
    theme: 
      light: [yeti, theme_light.scss]
      #dark: [darkly, theme_dark.scss]
    toc: true
    number_sections: true
header-includes:
  - |
    <script>
      document.querySelectorAll('a').forEach(function(link) {
        link.setAttribute('target', '_blank');
      });
    </script>
editor: source

